// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"time"
)

type Product struct {
	ID        int64
	Name      string
	Content   string
	Createdat time.Time
}
